#!/bin/bash
echo "=========================================="
echo "FAST APK CREATION FOR COINHUBX"
echo "=========================================="
echo ""
echo "Your options to get an APK RIGHT NOW:"
echo ""
echo "1. PWA Builder (Microsoft) - FASTEST"
echo "   https://www.pwabuilder.com/"
echo "   Enter: https://tradefix-preview.preview.emergentagent.com"
echo "   Click 'Package for Stores'"
echo "   Download Android APK"
echo "   Time: 2 minutes"
echo ""
echo "2. AppsGeyser - FREE"
echo "   https://appsgeyser.com/"
echo "   Choose 'Website'"
echo "   Enter URL: https://tradefix-preview.preview.emergentagent.com"
echo "   Download APK"
echo "   Time: 5 minutes"
echo ""
echo "Once downloaded, run:"
echo "cp ~/Downloads/YourApp.apk /app/webview-app/android/app/build/outputs/apk/release/app-release.apk"
echo ""
echo "=========================================="
